pipeline {
    agent {
        docker {
            image 'node:alpine3.19'
            args '-p 3000:3000'
            args '-u root:root'
        }
    }
    environment {
        CI = true
    }
    stages {
        stage ('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage ('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}
